version: '2.0'

services:

  # mysql 数据库服务
   postgresql:
     image: bitnami/postgresql:15
     volumes:
       - ./postgresql:/var/lib/postgresql
     environment:
       - POSTGRES_PASSWORD=password
       - POSTGRES_USER=postgres
       - POSTGRES_DB=odoo
     ports:
       - "5432:5432"


networks:
  default:
