version: '2.0'

services:
  # mysql 数据库服务
  mysql:
    image: mysql:5.7.28
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
networks:
  default:

