version: '2.0'

services:
  # mysql 数据库服务
  mysql:
    image: mysql:5.7.28
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  # mysql 数据库服务
  # mysql8:
  #   image: mysql:8.2.0
  #   volumes:
  #     - ./mysql_data_8:/var/lib/mysql
  #   environment:
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "33060:33060"
  #     - "3307:3306"

  redis:
    image: redis:latest
    command: redis-server --requirepass 123456
    # ports:
    #  - "6379:6379"
    volumes:
      - ./redis_data:/data

networks:
  default:

